// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUip3C0GwSK8G-xPTxQHNXPmKkVa3j7mk',
    appId: '1:564177947022:web:523680bd8b1c8c9e0ebcdf',
    messagingSenderId: '564177947022',
    projectId: 'sailstayapp2',
    authDomain: 'sailstayapp2.firebaseapp.com',
    storageBucket: 'sailstayapp2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaPBfU-s4Oz15ieSXCGYkOtNM0Of8fXYU',
    appId: '1:564177947022:android:44c23df7a8bb270d0ebcdf',
    messagingSenderId: '564177947022',
    projectId: 'sailstayapp2',
    storageBucket: 'sailstayapp2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAoxB2eb9o-jbAzHOoj5fHqv2anwPglIzw',
    appId: '1:564177947022:ios:2a614bffd8cd96ff0ebcdf',
    messagingSenderId: '564177947022',
    projectId: 'sailstayapp2',
    storageBucket: 'sailstayapp2.firebasestorage.app',
    iosBundleId: 'com.example.sailstayapp2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAoxB2eb9o-jbAzHOoj5fHqv2anwPglIzw',
    appId: '1:564177947022:ios:2a614bffd8cd96ff0ebcdf',
    messagingSenderId: '564177947022',
    projectId: 'sailstayapp2',
    storageBucket: 'sailstayapp2.firebasestorage.app',
    iosBundleId: 'com.example.sailstayapp2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUip3C0GwSK8G-xPTxQHNXPmKkVa3j7mk',
    appId: '1:564177947022:web:b4bbabc8ca5625320ebcdf',
    messagingSenderId: '564177947022',
    projectId: 'sailstayapp2',
    authDomain: 'sailstayapp2.firebaseapp.com',
    storageBucket: 'sailstayapp2.firebasestorage.app',
  );
}
